pip install pdfminer.six
pip install openai
pip install langchain
pip install python-dotenv
pip install matplotlib
pip install plotly
pip install pandas
pip install scipy
pip install scikit-learn
pip install tiktoken
pip install faiss-cpu
pip install streamlit